//Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;


import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;

import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class Httpscmt1testcmeetingcomweb3homexhtmlTest {
	private static WebDriver driver;
	private static Map<String, Object> vars;
	static JavascriptExecutor js;

	@BeforeAll
	public static void setUp() {
		WebDriverManager.chromedriver().setup();
		
		driver = new ChromeDriver();
		driver.manage().timeouts().implicitlyWait(Duration.ofMillis(5000));
		
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@AfterAll
	public static void tearDown() {
		driver.quit();
	}

	@Test
	public void httpscmt1testcmeetingcomweb3homexhtml() {
		driver.get("https://cmt1-test.c-meeting.com/web3/home");
		driver.manage().window().setSize(new Dimension(965, 935));
		driver.findElement(By.id("login-dropdown")).click();
		driver.findElement(By.id("emailField")).sendKeys("stefano.bandi@cefriel.com");
		driver.findElement(By.id("me-inv-login-box-but")).click();
		driver.findElement(By.cssSelector(".font-home-room_right_scroll")).click();
		driver.findElement(By.cssSelector("#\\-7K0vMqbKrt7FhS6lQpLLQ .myhome-room-meetme-button")).click();
		driver.findElement(By.cssSelector("#audio-popup-webcall-webcam-scroll .audio-popup-other-option:nth-child(3)"))
				.click();
		driver.findElement(By.cssSelector("#audio-popup-noAudio-button span")).click();
		driver.findElement(By.cssSelector("#audio-popup-noAudio-button > .audio-popup-button-flex")).click();
		driver.findElement(By.cssSelector(".icon-icon_exit")).click();
		driver.findElement(By.cssSelector("#exit-meeting .backCol6h")).click();
		driver.findElement(By.cssSelector(".backCol5 > span:nth-child(2)")).click();
		driver.findElement(By.cssSelector("#stop-meeting .backCol6h")).click();
		driver.findElement(By.cssSelector("#login-options-button > .loginImgHTML5")).click();
		driver.findElement(By.id("j_idt205:logout")).click();
	}

	@Test
	public void testMe() {
		driver.get("https://www.c-meeting.com");
		driver.quit();
	}
}
