package helperClasses;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.safari.SafariDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class TestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    //options.addArguments("--no-sandbox");
    //options.addArguments("--headless"); //!!!should be enabled for Jenkins
    //options.addArguments("--disable-dev-shm-usage")//!!!should be enabled for Jenkins
            options.addArguments("--use-fake-ui-for-media-stream");
            options.addArguments("--use-fake-device-for-media-stream");



    WebDriverManager.chromedriver().setup();

    driver = new ChromeDriver(options);
    driver.manage().timeouts().implicitlyWait(Duration.ofMillis(5000));

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
// Test name: test
    // Step # | name | target | value
    // 1 | open | /web3/home.xhtml |

    driver.get("https://cmt1-test.c-meeting.com/web3/home.xhtml");
    driver.manage().window().maximize();
    // 2 | click | id=login-dropdown |
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    //driver.findElement(By.xpath("//*[@id=\"login-dropdown\"]")).click();
    new Actions(driver).click(driver.findElement(By.xpath("//*[@id=\"login-dropdown\"]"))).perform();

    // 3 | click | id=emailField |
    //driver.findElement(By.id("emailField")).click();
    // 4 | type | id=emailField | dominik.markart@cefriel.com
    driver.findElement(By.id("emailField")).sendKeys("dominik.markart@cefriel.com");
    // 5 | type | id=passwordField | Cefriel1234
    driver.findElement(By.id("passwordField")).sendKeys("Cefriel1234");
    // 6 | sendKeys | id=passwordField | ${KEY_ENTER}
    driver.findElement(By.id("passwordField")).sendKeys(Keys.ENTER);
    // 7 | click | css=#B_mjIr0UAlUMg9x2yHmUdA .myhome-room-meetme-button |
    driver.findElement(By.cssSelector("#B_mjIr0UAlUMg9x2yHmUdA .myhome-room-meetme-button")).click();
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    // 8 | click | css=#audio-popup-webcall-webcam-button span |
    driver.findElement(By.cssSelector("#audio-popup-webcall-webcam-button span")).click();
    // 9 | click | css=.icon-icon_exit |
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    driver.findElement(By.cssSelector(".icon-icon_exit")).click();
    // 10 | click | css=#exit-meeting .backCol6h |
    driver.findElement(By.cssSelector("#exit-meeting .backCol6h")).click();
    // 11 | click | css=#login-options-button > .loginImgHTML5 |
    driver.findElement(By.cssSelector("#login-options-button > .loginImgHTML5")).click();
    // 12 | click | id=j_idt205:logout |
    driver.findElement(By.id("j_idt205:logout")).click(); }
}
